# Generated by Django 4.1.7 on 2023-06-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(default='2001-09-03'),
            preserve_default=False,
        ),
    ]
