# Generated by Django 4.1.7 on 2023-05-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dic', models.CharField(blank=True, max_length=100, null=True)),
                ('statuse', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('semptoms', models.CharField(blank=True, max_length=100, null=True)),
                ('pain', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('vomit', models.CharField(blank=True, max_length=100, null=True)),
                ('pee', models.CharField(blank=True, max_length=100, null=True)),
                ('heart', models.CharField(blank=True, max_length=100, null=True)),
                ('breath', models.CharField(blank=True, max_length=100, null=True)),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
