# Generated by Django 4.1.7 on 2023-06-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='dic',
            new_name='dis',
        ),
    ]
