# Generated by Django 4.1.7 on 2023-06-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_dic_exp_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
    ]
