# Generated by Django 4.1.7 on 2023-06-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='Money',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='payed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Money',
            field=models.BigIntegerField(default=1222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='payed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
