# Generated by Django 4.1.7 on 2023-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_prescription_money_remove_prescription_payed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Money',
            field=models.BigIntegerField(default=0),
        ),
    ]
